### ISSUE TITLE
Activation of Developer Mode not possible

### ISSUE THREAD

**Issue by lutzSul** [Somfy-Developer/Somfy-TaHoma-Developer-Mode#50] opened 2022-08-18 14:28 UTC
Unfortunately I cannot activate the developer mode for my box. I have a TaHoma Premium (V2). However, I can still see the picture of my previous box (V1) in my Somfy account, but with the correct number of the current box. There I can only unlock access for service cases but there is no developer mode switch. Is the TaHoma Switch (V3) required for Developer Mode or am I doing something else wrong?

**Comment by nitricware** [comment] 2022-08-27 12:53
I have a similar problem. In my account, the picture also does not match the box I have.

I own a Tahoma Connectivity Kit but old "folded" box is pictured in the account.

There's no button to activate developer account.

**Comment by Vogelschutzwarte** [comment] 2022-09-03 06:40
Same problem for my account. The activation box for the developer mode cannot scroll and has a fixed position, therefore no possibility to activate developer mode. I tried several platforms and browsers: Mac, iOS, Windows - same issue on all platforms.

**Comment by nitricware** [comment] 2022-09-03 07:07
Possible duplicate of issue #12

**Comment by Vogelschutzwarte** [comment] 2022-09-04 09:18
> Possible duplicate of issue #12

My issue is about the Somfy homepage and the „Somfy Account“ settings. I can see the option to activate the developer mode for my account, but I cannot confirm the popup message as the message does not allow to scroll and has a fixed position.

**Comment by llavorel-somfy** [comment] 2022-10-12 16:02
Hi @Vogelschutzwarte 
Would you be able to provide us a screenshot ?
What type of phone or computer are you using ?
Thank you

**Closed** 2024-02-13 14:20 UTC
